name: Man10Slot_15
version: ${project.version}
main: red.man10.man10slot_15.Man10Slot_15
api-version: 1.15
commands:
  mslot:
    description: Command no setsumei
    usage: /<command>
    permission: mslot.setting
permissions:
  mslot.use:
    default: true
  mslot.setting:
    default: false